# Generated by Django 5.2.4 on 2025-09-04 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='request_log_ip_addr_22f98c_idx'), models.Index(fields=['timestamp'], name='request_log_timesta_6625f0_idx'), models.Index(fields=['path'], name='request_log_path_5a9834_idx')],
            },
        ),
    ]
