# Generated by Django 5.2.4 on 2025-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['country'], name='request_log_country_6d9651_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['city'], name='request_log_city_a935c5_idx'),
        ),
    ]
