# Generated by Django 5.2.4 on 2025-09-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_requestlog_city_requestlog_country_requestlog_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.CharField(choices=[('high_volume', 'High request volume'), ('sensitive_access', 'Access to sensitive paths'), ('multiple_failures', 'Multiple authentication failures'), ('scanning', 'Port scanning behavior')], max_length=20)),
                ('request_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_offense', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'db_table': 'suspicious_ips',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['ip_address'], name='suspicious__ip_addr_3bcffd_idx'), models.Index(fields=['detected_at'], name='suspicious__detecte_c5ad7e_idx'), models.Index(fields=['is_active'], name='suspicious__is_acti_f1a4ed_idx')],
                'unique_together': {('ip_address', 'reason')},
            },
        ),
    ]
